language: java
env:
  global:
  - secure: L56SIMetEpiFWTI+lS2eu9DQ0xVNZJQ82hOqMOpqpEHOX438hXE5FrZIWemVlRZv75neR6cpJORpP8dbBVVfTnNEQQLSLLhBJQgZueJtM+V0M3rK1TqJM7FE/Q64tsVc/OBlTibQRU5dX1e8rQwYVxulf0F+JmGFRAqJZ+fYu5EI7tpOaFya+W9rG1j9kQya1mdvInL+XbLvCK2G88yVPlHRdXGKUhVJ11+++iWEODuoIxgpejAQ+Yst9/jCRdHmFXpO0/KLo015kx9txKtgSOctIg3gAAa+Qlxx1lcMpbYQR25kutUrmK5Zjqwfa0XCwYg50nMtvI3QncSvZNSG9rtHzDtU9hXdOX87e4/ymSdJtxbszao9m2SU9GP6f7hz5UFetUvPYYRlIadvHdPEL55EFTNFJ3Mtlt3HPpir7y1fd8p+GKba725a+hd28AcQF+l/ZYDdT3YXbR6Aukj/x1hydMCM9Thv7J71/GnQ1nM3f7+T9eGffyKgauS6zwT/SD+yKPa9uQSMICGr4aBTiKpq6GVjfgKyhziHuRUWDwVv62/OaNIonxCbT72pqooAal9ZkJrdxWy90vZiI0YvCGJ62h9MUhq52tlmcThdLjBJ4zCdT0WohXf6R2ufO7w3RIKGa9zOKoFjmFKZxtYG0uCPV1DEbb8MPuywd1Lj7+U=
  - secure: M17YPsQidJR6jokEC6CC/W48ugBI8lBmuIyYx7Yucx3DeP6M+dokACIXm35L7pbUkHnkA4/in0J2vqYea6p4KV6ZpTMPzl4L5kxuohoDSh6wVwMCk+ROPQbrsq82tJHAl643uYO+VsNIk+OdFZ5uoBHUfCpRyxBkv2KuXzDfTtK1iEaJ0xi8heIqcFTqVCIe/VoSQN6gjl8ipTtx7ILtJw9wzRmbJd3Kq0TJh6bAj7FtP1k8uzW46TtwaJKYzUYgMp6Vb/cbuzcd9whIEM/ul32g8xz6x3Kozph4uKLsoa6+eDU/liQLO1a2poi8OyG9TzU0h2PrH0R2m+nhxo4QHKIVeAQqzDnXqdyc0cRcdqyaC7jxwlnOKfJsKN7zjj1wPD7bgt8rYH2wLf42y9C+0Mr0OpQpZFmclIt8m6eKw0Ol9kSOOGWBeIb9yJa6sjtTxobNvYrTMhZAbDmy5Byo84P5Aw7asaWbz2hyC7K680tHXv5WkZxd6Qm/9wi+VXTqVoBsyuoC2N7IBsOHAwqVbmBnBsqDN3uCku9cZdwCDKBGRlIGOYl/6kNF2hYK9KRyNrDC41W3S86GUIHlst13g51mW3s5W1jTjdmAHi0hQYluX7MlIneb/ZLu8lhrBzyEignpbosO2zHJSeXu5ETP9tmpKGa4dhxkwIC6pPo84OE=
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: modernmaster/neo4j-visualisations
      description: Build submitted via Travis CI
    notification_email: diesel_baz@hotmail.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: master
after_success:
- bash <(curl -s https://codecov.io/bash)
